###############################################
### Dynamic Traefik V2 Configuration (FILE) ###
###############################################

## HTTP Middlewares
http:
  middlewares:
    hsts-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        forceStsHeader: true
        referrerPolicy: same-origin
        customResponseHeaders:
          permissions-Policy: vibrate=(self), geolocation=(self), midi=(self), notifications=(self), push=(self), microphone=(), $
          X-Permitted-Cross-Domain-Policies: none
          expect-ct: max-age=604800, report-uri="https://oak.ct.letsencrypt.org/2021"

    ## Primitive Middlewares
    user-auth:
      basicAuth:
        usersFile: ".htpasswd/users"

    gzip:
      compress: {}

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    default-secure-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: deny
          Strict-Transport-Security: "max-age=31536000 ; includeSubDomains"
          X-Content-Type-Options: nosniff
          Referrer-Policy: no-referrer
          sslRedirect: true

    portal-service-secure-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: SAMEORIGIN
          Referrer-Policy: strict-origin-when-cross-origin

    autodetectContenttype: # needed for traefik v3 - see https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/
      contentType: {}
      
    ## Chain Middlewares
    basic-auth-secured:
      chain:
        middlewares:
          - user-auth
          - default-secure-headers
          - rate-limit
          - gzip

    no-auth-secured:
      chain:
        middlewares:
          - default-secure-headers
          - rate-limit
          - gzip'

    webSecureByIp:
      ipAllowList:
        sourceRange:
          - 82.66.56.51

    webSecureByIpLarge:
      ipAllowList:
        sourceRange:
          - 82.66.56.51
          - 88.176.150.74

## TLS 1.2 / TLS 1.3
tls:
  options:
    mintls12:
      minVersion: VersionTLS12 # <======= TLS 1.2 / TLS 1.3
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 # TLS 1.2
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 # TLS 1.2
        - TLS_AES_256_GCM_SHA384 # TLS 1.3
        - TLS_CHACHA20_POLY1305_SHA256 # TLS 1.3
        - TLS_FALLBACK_SCSV # TLS FALLBACK
      curvePreferences:
        - secp521r1
        - secp384r1
    modern:
      minVersion: VersionTLS13

## TCP
# Accepts request from defined IP
tcp:
  middlewares:
    tcpSecureByIp:
      ipAllowList:
        sourceRange:
          - 82.66.56.51
          - 88.176.150.74
